spring:
  profiles:
    active: cloud
---
spring:
  profiles: cloud
  datasource:
    url: ${cloud.services.mysql.connection.uri}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    generate-ddl: true
  application:
    name: s3-broker
management:
  contextPath: /management
security:
  basic:
    enabled: true
aws:
  access-key-id: replace
  secret-access-key: replace
---
spring:
  profiles: test
  jpa:
    database: H2
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:h2:mem:db"
aws:
  access-key-id: replace
  secret-access-key: replace